### ISSUE TITLE
fail to load config.json: JSONDecodeError: Expecting value: line 3 column 24 (char 62)

### ISSUE THREAD

**Issue by tbs17** [kaushaltrivedi/fast-bert#120]
Hi Kaushal,

I'm trying to use fast_bert to deploy BERT ON aws. I have put config.json file under the pretrained model path. When I load the bertlearner object by below:
**BertLearner.from_pretrained_model(databunch,BERT_PRETRAINED_PATH,metrics,device,
        logger,finetuned_wgts_path=None,is_fp16=args['fp16'],loss_scale=args['loss_scale'],
        multi_gpu=multi_gpu,multi_label=True)**

**I got the error message like:**

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-34-182283fdb238> in <module>()
      3 learner=BertLearner.from_pretrained_model(databunch,BERT_PRETRAINED_PATH,metrics,device,
      4         logger,finetuned_wgts_path=None,is_fp16=args['fp16'],loss_scale=args['loss_scale'],
----> 5         multi_gpu=multi_gpu,multi_label=True)

6 frames
/usr/local/lib/python3.6/dist-packages/fast_bert/learner.py in from_pretrained_model(dataBunch, pretrained_path, metrics, device, logger, finetuned_wgts_path, multi_gpu, is_fp16, loss_scale, warmup_proportion, fp16_opt_level, grad_accumulation_steps, multi_label, max_grad_norm, use_amp_optimizer, model_type)
     87             model = model_class[1].from_pretrained(pretrained_path, 
     88                                                                   num_labels = len(dataBunch.labels),
---> 89                                                                   state_dict=model_state_dict)
     90         else:
     91             model = model_class[0].from_pretrained(pretrained_path, 

/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    285                 cache_dir=cache_dir, return_unused_kwargs=True,
    286                 force_download=force_download,
--> 287                 **kwargs
    288             )
    289         else:

/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    152 
    153         # Load config
--> 154         config = cls.from_json_file(resolved_config_file)
    155 
    156         if hasattr(config, 'pruned_heads'):

/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py in from_json_file(cls, json_file)
    185         with open(json_file, "r", encoding='utf-8') as reader:
    186             text = reader.read()
--> 187         return cls.from_dict(json.loads(text))
    188 
    189     def __eq__(self, other):

/usr/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/usr/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 3 column 24 (char 62)

I'm running this on colab and have run databunch function correctly. So i assume everything required for that function to run is correct such as data path. 

Can you give guidance on how to troubleshoot? Thank you!

**Comment by jordanparker6** [comment]
I am having a similar issue for AWS SageMaker on training. 

The outputted error is as follows:

`AlgorithmError: Exception during training: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last): File "/opt/ml/code/train", line 154, in train label_col = json.loads(training_config["label_col"]) File "/usr/lib/python3.7/json/__init__.py", line 348, in loads return _default_decoder.decode(s) File "/usr/lib/python3.7/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

My training_config.json file is as follows:

{
    "run_text": "text-classifier", 
    "finetuned_model": null, 
    "do_lower_case": "True", 
    "train_file": "train.csv", 
    "val_file": "val.csv", 
    "label_file": "labels.csv", 
    "text_col": "text", 
    "label_col": "label", 
    "multi_label": "False", 
    "grad_accumulation_steps": "1", 
    "fp16_opt_level": "O1", 
    "fp16": "True", 
    "model_type": "roberta", 
    "model_name": "roberta-base", 
    "logging_steps": "300"
}

Looking at the train file, the json.loads(training_config["label_col"])  should be skipped due to the mulit_label=False...

Any help would be appreciated...

**Comment by jordanparker6** [comment]
My issue looks to be connected to 

`if  bool(training_config['multi_label']) == True:`

With the config as a string, bool converts the result to True each time and this results in a parsing error in the subsequent lines.

**Comment by jordanparker6** [comment]
It appears that my error was due to my training_config.json file not being formatted with JSON consistent Boolean values. False and True were read as strings and brought about an error.
