### ISSUE TITLE
UnicodeDecodeError when attempting to instantiate BertClassificationPredictor with model_path pointing to saved model

### ISSUE THREAD

**Issue by aaronbriel** [kaushaltrivedi/fast-bert#130]
I created a learner from the 'bert-base-uncased' pre-trained model and successfully ran the fit function on it with a set of my own custom data. I successfully ran validate and save_model as well, the latter of which generated models/output/model_out/pytorch_model.bin. 

When I attempt to load a BertClassificationPredictor with model_path pointing to this model, however, calling predict fails with the stack trace below. Calling predict with model_path set to 'bert-base-uncased' is successful. I'm assuming based on https://github.com/huggingface/transformers/issues/728 that the issue is due to the absence of any vocab.txt file, but none was generated after saving the model.

Stack trace:
Traceback (most recent call last):
  File "runner.py", line 168, in <module>
    predictions = runner.predict(list(pd.read_csv('./data/test.csv')['ReviewText'].values), multi_label=True)
  File "runner.py", line 114, in predict
    multi_label=multi_label
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/fast_bert/prediction.py", line 38, in __init__
    self.learner = self.get_learner()
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/fast_bert/prediction.py", line 45, in get_learner
    self.model_path, do_lower_case=self.do_lower_case)
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 282, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 411, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/tokenization_bert.py", line 159, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/tokenization_bert.py", line 93, in load_vocab
    tokens = reader.readlines()
  File "/Users/aaronbriel/ai/text-classifier/.venv/bin/../lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
make: *** [test] Error 1

**Comment by sbmaruf** [comment]
Same issue here. @aaronbriel

**Comment by sbmaruf** [comment]
The error issued from here,
`https://github.com/huggingface/transformers/blob/master/transformers/tokenization_bert.py#L92`
If you print the `vocab_file` most likely you will find the vocab file as your pretrained model address. 
For me, I have solved the problem by sending a value to `args.tokenizer_name` parameter to my pretrained `model_name`.

@aaronbriel  you can try, 

```
tokenizer = tokenizer_class.from_pretrained("bert-base-uncased",
                                                do_lower_case=args.do_lower_case,
                                                cache_dir=None)
```

**Comment by aaronbriel** [comment]
Not sure I follow. I already noted that prediction works if I pass a pretrain model (not my own). For example, the following works:
```
            predictor = BertClassificationPredictor(
                model_path= 'bert-base-uncased',
                label_path=label_path,
                multi_label=multi_label
            )
```
I want to be able to call predict or predict_batch using a predictor that uses the model I trained / fine-tuned.

**Comment by aaronbriel** [comment]
I forked fast_bert and tried setting up tokenizer to use the tokenizer with one of the set paths then passing the model path to the BertLearner. After fixing the scheduler logic in fast_bert's learner_util (I'll be submitting a PR soon), config is still set with "vocab_size": -1 in config.json, presumably due to the initial issue of no vocab.txt file being generated after training. Here is the latest stack trace:
`11/30/2019 17:02:23 - INFO - transformers.modeling_utils -   loading weights file models/output/model_out/pytorch_model.bin
Traceback (most recent call last):
  File "runner.py", line 172, in <module>
    predictions = runner.predict(texts, multi_label=True)
  File "runner.py", line 116, in predict
    multi_label=multi_label
  File "/Users/aaronbriel/pinklion/ai/text-classifier/.venv/src/fast-bert/fast_bert/prediction.py", line 44, in __init__
    self.learner = self.get_learner()
  File "/Users/aaronbriel/pinklion/ai/text-classifier/.venv/src/fast-bert/fast_bert/prediction.py", line 67, in get_learner
    multi_label=self.multi_label, logging_steps=0)
  File "/Users/aaronbriel/pinklion/ai/text-classifier/.venv/src/fast-bert/fast_bert/learner_cls.py", line 69, in from_pretrained_model
    model = model_class[1].from_pretrained(pretrained_path, config=config, state_dict=model_state_dict)
  File "/Users/aaronbriel/pinklion/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/modeling_utils.py", line 392, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/Users/aaronbriel/pinklion/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/modeling_bert.py", line 997, in __init__
    self.bert = BertModel(config)
  File "/Users/aaronbriel/pinklion/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/modeling_bert.py", line 609, in __init__
    self.embeddings = BertEmbeddings(config)
  File "/Users/aaronbriel/pinklion/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/modeling_bert.py", line 152, in __init__
    self.word_embeddings = nn.Embedding(config.vocab_size, config.hidden_size, padding_idx=0)
  File "/Users/aaronbriel/pinklion/ai/text-classifier/.venv/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 97, in __init__
    self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 768]
make: *** [test] Error 1`

**Comment by aaronbriel** [comment]
I forked fast_bert and tried setting up tokenizer to use the tokenizer with one of the set paths then passing the model path to the BertLearner. After fixing the scheduler logic in fast_bert's learner_util (I'll be submitting a PR soon), config is still set with "vocab_size": -1 in config.json, presumably due to the initial issue of no vocab.txt file being generated after training. Here is the latest stack trace:
11/30/2019 17:02:23 - INFO - transformers.modeling_utils -   loading weights file models/output/model_out/pytorch_model.bin
Traceback (most recent call last):
  File "runner.py", line 172, in <module>
    predictions = runner.predict(texts, multi_label=True)
  File "runner.py", line 116, in predict
    multi_label=multi_label
  File "/Users/aaronbriel/ai/text-classifier/.venv/src/fast-bert/fast_bert/prediction.py", line 44, in __init__
    self.learner = self.get_learner()
  File "/Users/aaronbriel/ai/text-classifier/.venv/src/fast-bert/fast_bert/prediction.py", line 67, in get_learner
    multi_label=self.multi_label, logging_steps=0)
  File "/Users/aaronbriel/ai/text-classifier/.venv/src/fast-bert/fast_bert/learner_cls.py", line 69, in from_pretrained_model
    model = model_class[1].from_pretrained(pretrained_path, config=config, state_dict=model_state_dict)
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/modeling_utils.py", line 392, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/modeling_bert.py", line 997, in __init__
    self.bert = BertModel(config)
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/modeling_bert.py", line 609, in __init__
    self.embeddings = BertEmbeddings(config)
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/transformers/modeling_bert.py", line 152, in __init__
    self.word_embeddings = nn.Embedding(config.vocab_size, config.hidden_size, padding_idx=0)
  File "/Users/aaronbriel/ai/text-classifier/.venv/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 97, in __init__
    self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 768]
make: *** [test] Error 1

**Comment by aaronbriel** [comment]
vocab.txt is now being generated after training. This issue is resolved.
