### ISSUE TITLE
ImportError: cannot import name 'ConstantLRSchedule'

### ISSUE THREAD

**Issue by kleysonr** [kaushaltrivedi/fast-bert#133]
Doing the following steps to install the fast-bert:

1. pip install fast-bert
2. git clone https://github.com/NVIDIA/apex
3. cd apex
4. pip install -v --no-cache-dir ./
5. create train.py

```python
from fast_bert.data_cls import BertDataBunch

DATA_PATH = 'data'
LABEL_PATH = 'data'

databunch = BertDataBunch(DATA_PATH, LABEL_PATH,
                          tokenizer='bert-base-multilingual-uncased',
                          train_file='train.csv',
                          val_file='val.csv',
                          label_file='labels.csv',
                          text_col='text',
                          label_col='label',
                          batch_size_per_gpu=16,
                          max_seq_length=512,
                          multi_gpu=True,
                          multi_label=False,
                          model_type='bert')
```
6. run it

Getting the following error:

```
Traceback (most recent call last):
  File "/home/kleysonr/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/kleysonr/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/kleysonr/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/dev/python/mestrado/aula9/train.py", line 1, in <module>
    from fast_bert.data_cls import BertDataBunch
  File "/home/kleysonr/.virtualenvs/fastai/lib/python3.6/site-packages/fast_bert/__init__.py", line 5, in <module>
    from .learner_cls import BertLearner
  File "/home/kleysonr/.virtualenvs/fastai/lib/python3.6/site-packages/fast_bert/learner_cls.py", line 3, in <module>
    from .learner_util import Learner
  File "/home/kleysonr/.virtualenvs/fastai/lib/python3.6/site-packages/fast_bert/learner_util.py", line 4, in <module>
    from transformers import (ConstantLRSchedule,
ImportError: cannot import name 'ConstantLRSchedule'
```

Installed python modules:

```
$ pip freeze
apex==0.1
beautifulsoup4==4.8.1
blis==0.4.1
boto3==1.10.28
botocore==1.13.28
Bottleneck==1.3.1
catalogue==0.0.8
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cycler==0.10.0
cymem==2.0.3
dataclasses==0.7
docutils==0.15.2
fast-bert==1.4.4
fastai==1.0.59
fastprogress==0.1.22
idna==2.8
importlib-metadata==0.23
jmespath==0.9.4
joblib==0.14.0
kiwisolver==1.1.0
matplotlib==3.1.2
more-itertools==7.2.0
murmurhash==1.0.2
numexpr==2.7.0
numpy==1.17.4
nvidia-ml-py3==7.352.0
packaging==19.2
pandas==0.25.3
Pillow==6.2.1
plac==1.1.3
preshed==3.0.2
protobuf==3.11.0
pyparsing==2.4.5
python-dateutil==2.8.1
pytorch-lamb==1.0.0
pytz==2019.3
PyYAML==5.1.2
regex==2019.11.1
requests==2.22.0
s3transfer==0.2.1
sacremoses==0.0.35
scikit-learn==0.21.3
scipy==1.3.3
sentencepiece==0.1.83
six==1.13.0
sklearn==0.0
soupsieve==1.9.5
spacy==2.2.3
srsly==0.2.0
tensorboardX==1.9
thinc==7.3.1
torch==1.3.1
torchvision==0.4.2
tqdm==4.39.0
transformers==2.2.0
urllib3==1.25.7
wasabi==0.4.0
zipp==0.6.0
```

**Comment by zampierimatteo91** [comment]
I had this problem yesterday.

Apparently, in version 2.2.0 of transformers, they switched from classes to functions, so now they use get_constant_scheduler().

Try installing transformers 2.0.0
`pip install transformers==2.0.0`

**Comment by kaushaltrivedi** [comment]
Update to fast-Bert to support 2.2 version of transformers coming in a day or two. In the meantime downgrade to transformers 2.1.

**Comment by aaronbriel** [comment]
@kaushaltrivedi I did PR #135 but just noticed this. If you already handled this I can delete the PR...

**Comment by kaushaltrivedi** [comment]
This has been fixed. You can delete the PR. Thanks so much for contributing
