### ISSUE TITLE
Error running build_and_run.sh

### ISSUE THREAD

**Issue by emtropyml** [kaushaltrivedi/fast-bert#144]
Step 6/22 : RUN cd /tmp &&     curl -O https://bootstrap.pypa.io/get-pip.py &&                                                                                             python get-pip.py 'pip<=18.1' && rm get-pip.py
 ---> Running in 1de8cb480d76
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1734k  100 1734k    0     0  24.1M      0 --:--:-- --:--:-- --:--:-- 23.8M
Traceback (most recent call last):
  File "get-pip.py", line 22318, in <module>
    main()
  File "get-pip.py", line 198, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip._internal.main
  File "/tmp/tmpzbhzzx_l/pip.zip/pip/_internal/main.py", line 13, in <module>
  File "/tmp/tmpzbhzzx_l/pip.zip/pip/_internal/cli/autocompletion.py", line 11,                                                                                         in <module>
  File "/tmp/tmpzbhzzx_l/pip.zip/pip/_internal/cli/main_parser.py", line 7, in <                                                                                        module>
  File "/tmp/tmpzbhzzx_l/pip.zip/pip/_internal/cli/cmdoptions.py", line 19, in <                                                                                        module>
ModuleNotFoundError: No module named 'distutils.util'
The command '/bin/sh -c cd /tmp &&     curl -O https://bootstrap.pypa.io/get-pip                                                                                        .py &&     python get-pip.py 'pip<=18.1' && rm get-pip.py' returned a non-zero c                                                                                        ode: 1
Error response from daemon: No such image: fluent-sagemaker-fast-bert:1.0-gpu-py                                                                                        36
The push refers to repository [182918221797.dkr.ecr.us-east-1.amazonaws.com/flue                                                                                        nt-sagemaker-fast-bert]
An image does not exist locally with the tag: 182918221797.dkr.ecr.us-east-1.ama                                                                                        zonaws.com/fluent-sagemaker-fast-bert

**Comment by raiyani** [comment]
Same error for me... Thanks.

**Comment by emtropyml** [comment]
I found a fix to this. Just add the following code in the Dockerfile before the line "# Install pip" :

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python3-distutils

**Comment by raiyani** [comment]
Indeed... that got me past this hurdle. Thanks a lot @emtropyml!
