### ISSUE TITLE
SageMaker predict error... botocore.errorfactory.ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation

### ISSUE THREAD

**Issue by raiyani** [kaushaltrivedi/fast-bert#153]
I am running the SageMaker notebook (toxic_comments_sagemaker.ipynb). 

```
predictor = estimator.deploy(1, 
                             'ml.m5.large', 
                             endpoint_name='toxic-comments', 
                             update_endpoint=False, 
                             serializer=json_serializer)

response = predictor.predict("This book sucks and I hate it.")
```
I get the following error message for the predict call:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.7/site-packages/sagemaker/predictor.py", line 110, in predict
>     response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
>   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 272, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 576, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> botocore.errorfactory.ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
> ". See https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpoints/toxic-comments in account xxxxxxxxxxxx for more information.
> 

The view from AWS Cloudwatch:

<img width="1473" alt="Screen Shot 2019-12-15 at 10 18 20 PM" src="https://user-images.githubusercontent.com/6283995/70883831-13b79380-1f89-11ea-9197-cae7aec67bfd.png">

Can you please help? Thanks!

**Comment by raiyani** [comment]
This worked:
response = predictor.predict({'text':'You are a horrible human being'})

Thanks for the tutorial @kaushaltrivedi
