### ISSUE TITLE
AlgorithmError: Exception during training: expected string or bytes-like object

### ISSUE THREAD

**Issue by punit121** [kaushaltrivedi/fast-bert#158]
- INFO - root -   Writing example 0 of 6382
Exception during training: expected string or bytes-like object
Traceback (most recent call last):
  File "/opt/ml/code/train", line 175, in train
    logger=logger,
  File "/opt/conda/lib/python3.7/site-packages/fast_bert/data_cls.py", line 463, in __init__
    train_examples, "train", no_cache=self.no_cache
  File "/opt/conda/lib/python3.7/site-packages/fast_bert/data_cls.py", line 590, in get_dataset_from_examples
    logger=self.logger,
  File "/opt/conda/lib/python3.7/site-packages/fast_bert/data_cls.py", line 143, in convert_examples_to_features
    tokens_a = tokenizer.tokenize(example.text_a)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 657, in tokenize
    text = lowercase_text(text)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 654, in lowercase_text
    t)
  File "/opt/conda/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by BenFielding** [comment]
I fixed this by explicitly casting to string within the TextProcessor - I've created a pull request with my changes  (#167 ).

Otherwise, the changes are below:

Changed this line:
https://github.com/kaushaltrivedi/fast-bert/blob/e3c4c64dbc146e7c6748d990b6984c4fa2bf5eeb/fast_bert/data_cls.py#L315

From:
`guid=row.index, text_a=row[text_col], label=None`
To:
`guid=row.index, text_a=str(row[text_col]), label=None`

And/or this line:
https://github.com/kaushaltrivedi/fast-bert/blob/e3c4c64dbc146e7c6748d990b6984c4fa2bf5eeb/fast_bert/data_cls.py#L324

From:
`guid=row.index, text_a=row[text_col], label=str(row[label_col])`
To:
`guid=row.index, text_a=str(row[text_col]), label=str(row[label_col])`


The above assumes you're doing single-label classification, if it's multi-label and it's the same error then the equivalent lines in `MultiLabelTextProcessor` will likely need editing similarly (and another pull request).
