### ISSUE TITLE
SageMaker: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### ISSUE THREAD

**Issue by paulfsheridan** [kaushaltrivedi/fast-bert#182]
I'm trying to deploy fast-bert on AWS SageMaker via the tutorial here: https://medium.com/@kaushaltrivedi/train-and-deploy-mighty-transformer-nlp-models-using-fastbert-and-aws-sagemaker-cc4303c51cf3

But when I deploy the Docker image I receive the following error

```
r: Exception during training: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "/opt/ml/code/train", line 209, in train
    logging_steps=int(training_config["logging_steps"]),
  File "/opt/conda/lib/python3.7/site-packages/fast_bert/learner_cls.py", line 154, in from_pretrained_model
    model.to(device)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 425, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 2
```

I'm really not sure where to go from here? From reading the Dockerbuild files it's grabbing CUDA 10.1. Any suggestions would be greatly welcomed.

**Comment by AndreasNeo** [comment]
# Are you trying to fit the model on local mode?
