### ISSUE TITLE
GPU-Memory Error | DistilBERT | GTX 1080Ti

### ISSUE THREAD

**Issue by jordanparker6** [kaushaltrivedi/fast-bert#76]
Hi,

I am having a GPU memory allocation error with Pytorch.

I have checked that there are no GPU processes running before execution. 

Please note that it appears to fail without all the GPU RAM being allocated.

Is it possible to run DistilBert on 11GB of GPU RAM?

I have turned fp16 off due to issues with the apex install on Windows. 

```
I1002 00:56:47.708032 12396 file_utils.py:39] PyTorch version 1.2.0 available.
I1002 00:56:48.017031 12396 modeling_xlnet.py:194] Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
I1002 00:56:49.467295 12396 tokenization_utils.py:373] loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at C:\Users\jorda\.cache\torch\transformers\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
I1002 00:56:49.491297 12396 data_cls.py:427] Loading features from cached file lm_data\cache\cached_distilbert_train_multi_class_512
I1002 00:56:49.621307 12396 data_cls.py:427] Loading features from cached file lm_data\cache\cached_distilbert_dev_multi_class_512
I1002 00:56:50.658936 12396 configuration_utils.py:151] loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-config.json from cache at C:\Users\jorda\.cache\torch\transformers\a41e817d5c0743e29e86ff85edc8c257e61bc8d88e4271bb1b243b6e7614c633.1ccd1a11c9ff276830e114ea477ea2407100f4a3be7bdc45d37be9e37fa71c7e
I1002 00:56:50.658936 12396 configuration_utils.py:168] Model config {
  "activation": "gelu",
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": null,
  "hidden_dim": 3072,
  "initializer_range": 0.02,
  "max_position_embeddings": 512,
  "n_heads": 12,
  "n_layers": 6,
  "num_labels": 5,
  "output_attentions": false,
  "output_hidden_states": false,
  "pruned_heads": {},
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "torchscript": false,
  "use_bfloat16": false,
  "vocab_size": 30522
}

I1002 00:56:51.674376 12396 modeling_utils.py:337] loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-pytorch_model.bin from cache at C:\Users\jorda\.cache\torch\transformers\7b8a8f0b21c4e7f6962451c9370a5d9af90372a5f64637a251f2de154d0fc72c.c2015533705b9dff680ae707e205a35e2860e8d148b45d35085419d74fe57ac5
I1002 00:56:53.022003 12396 modeling_utils.py:405] Weights of DistilBertForSequenceClassification not initialized from pretrained model: ['pre_classifier.weight', 'pre_classifier.bias', 'classifier.weight', 'classifier.bias']
I1002 00:56:53.022003 12396 modeling_utils.py:408] Weights from pretrained model not used in DistilBertForSequenceClassification: ['vocab_transform.weight', 'vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_projector.bias']
lm_model_distilbert\tensorboard
I1002 00:56:55.387261 12396 learner_cls.py:259] ***** Running training *****
I1002 00:56:55.387261 12396 learner_cls.py:260]   Num examples = 1780
I1002 00:56:55.387261 12396 learner_cls.py:261]   Num Epochs = 20
I1002 00:56:55.387261 12396 learner_cls.py:263]   Total train batch size (w. parallel, distributed & accumulation) = 16
I1002 00:56:55.387261 12396 learner_cls.py:264]   Gradient Accumulation steps = 1
I1002 00:56:55.387261 12396 learner_cls.py:265]   Total optimization steps = 2240
Traceback (most recent call last):
  File "C:\Users\jorda\OneDrive\Documents\Programs\applications\document_classifier\BERT\HuggingFace\main.py", line 69, in <module>
    optimizer_type="lamb")
  File "C:\Users\jorda\AppData\Roaming\Python\Python37\site-packages\fast_bert\learner_cls.py", line 299, in fit
    loss.backward()
  File "C:\Users\jorda\AppData\Roaming\Python\Python37\site-packages\torch\tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\jorda\AppData\Roaming\Python\Python37\site-packages\torch\autograd\__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 11.00 GiB total capacity; 8.65 GiB already allocated; 72.32 MiB free; 98.09 MiB cached)
[Finished in 12.527s]
```

**Comment by kaushaltrivedi** [comment]
in this case the easiest option will be to reduce the batch size to 8.  Although I am quite surprised that you get out of memory error on batch size of 16.  Can you clear the CUDA cache and try again.

**Comment by jordanparker6** [comment]
@kaushaltrivedi thanks again.

Clearing the CUDA cache didn't work but changing the batch size did.
