### ISSUE TITLE
RuntimeError: shape '[-1, 153165]' is invalid for input of size 48

### ISSUE THREAD

**Issue by C24IO** [kaushaltrivedi/fast-bert#99]
https://github.com/kaushaltrivedi/fast-bert/blob/25b18dcacad60d698d0a499f33a39d5584f6e153/sample_notebooks/new-toxic-multilabel.ipynb#L616
```


../models/output/tensorboard
10/22/2019 20:51:30 - INFO - root -   ***** Running training *****
10/22/2019 20:51:30 - INFO - root -     Num examples = 159571
10/22/2019 20:51:30 - INFO - root -     Num Epochs = 6
10/22/2019 20:51:30 - INFO - root -     Total train batch size (w. parallel, distributed & accumulation) = 64
10/22/2019 20:51:30 - INFO - root -     Gradient Accumulation steps = 1
10/22/2019 20:51:30 - INFO - root -     Total optimization steps = 14964

0.00% [0/6 00:00<00:00]
Interrupted

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-dbbd575bee7f> in <module>()
----> 1 learner.fit(args.num_train_epochs, args.learning_rate, validate=True)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fast_bert/learner_cls.py in fit(self, epochs, lr, validate, schedule_type, optimizer_type)
    219                     inputs['token_type_ids'] = batch[2]
    220 
--> 221                 outputs = self.model(**inputs)
    222                 loss = outputs[0]  # model outputs are always tuple in pytorch-transformers (see doc)
    223 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    150             return self.module(*inputs[0], **kwargs[0])
    151         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
--> 152         outputs = self.parallel_apply(replicas, inputs, kwargs)
    153         return self.gather(outputs, self.output_device)
    154 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py in parallel_apply(self, replicas, inputs, kwargs)
    160 
    161     def parallel_apply(self, replicas, inputs, kwargs):
--> 162         return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
    163 
    164     def gather(self, outputs, output_device):

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py in parallel_apply(modules, inputs, kwargs_tup, devices)
     83         output = results[i]
     84         if isinstance(output, ExceptionWrapper):
---> 85             output.reraise()
     86         outputs.append(output)
     87     return outputs

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/_utils.py in reraise(self)
    383             # (https://bugs.python.org/issue2651), so we work around it.
    384             msg = KeyErrorMessage(msg)
--> 385         raise self.exc_type(msg)

RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fast_bert/modeling.py", line 226, in forward
    labels.view(-1, self.num_labels))
RuntimeError: shape '[-1, 153165]' is invalid for input of size 48



```

**Comment by C24IO** [comment]
Closing this - it was because of the wrong label file supplied. Using the sample_data folder to check against your data is highly recommended.

**Comment by lanxingdouble** [comment]
I also face this problem.
![image](https://user-images.githubusercontent.com/18391135/70508149-cd1d0000-1b68-11ea-854d-2dda2d07bc8a.png)
But, my labels are some numbers, they are quite easy. I am sure ,they are right. But I still get this error.
![image](https://user-images.githubusercontent.com/18391135/70508297-29801f80-1b69-11ea-872a-10aeaa76758c.png)
![image](https://user-images.githubusercontent.com/18391135/70508337-3e5cb300-1b69-11ea-886b-209660cdd4f0.png)
![image](https://user-images.githubusercontent.com/18391135/70508405-5a605480-1b69-11ea-88b1-4d1630a84080.png)

**Comment by mohammedayub44** [comment]
@C24IO  How did you happen to troubleshoot the issue to lables file. Any help appreciated. Thanks !

**Comment by YanLiang1102** [comment]
this might be caused by the cache training data has different config for u current traininng
